### ISSUE TITLE
Failed to process transcription on Mac from PyCharm

### ISSUE THREAD

**Issue by modgeosys** [voqal/voqal#57]
2019 MacBook Pro (Intel, 32Gb RAM), same configuration as Ubuntu, latest macOS, latest PyCharm.  Receive following exception every time I speak a prompt (Voqal listens, but never comes through with a response):

Failed to process transcription

dev.voqal.rv: closed
at [dev.voqal.sI](http://dev.voqal.si/).a(SourceFile:52)
at dev.voqal.sI.a(SourceFile:23)
at dev.voqal.sI$b.invokeSuspend(SourceFile)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.IllegalStateException: closed
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at io.ktor.utils.io.ExceptionUtilsJvmKt$createConstructor$$inlined$safeCtor$1.invoke(ExceptionUtilsJvm.kt:103)
at io.ktor.utils.io.ExceptionUtilsJvmKt$createConstructor$$inlined$safeCtor$1.invoke(ExceptionUtilsJvm.kt:90)
at io.ktor.utils.io.ExceptionUtilsJvmKt.tryCopyException(ExceptionUtilsJvm.kt:45)
at io.ktor.utils.io.ByteBufferChannelKt.rethrowClosed(ByteBufferChannel.kt:2404)
at io.ktor.utils.io.ByteBufferChannelKt.access$rethrowClosed(ByteBufferChannel.kt:1)
at io.ktor.utils.io.ByteBufferChannel.setupStateForRead(ByteBufferChannel.kt:297)
at io.ktor.utils.io.ByteBufferChannel.readAsMuchAsPossible(ByteBufferChannel.kt:2443)
at io.ktor.utils.io.ByteBufferChannel.readAvailable$suspendImpl(ByteBufferChannel.kt:695)
at io.ktor.utils.io.ByteBufferChannel.readAvailable(ByteBufferChannel.kt)
at io.ktor.client.engine.java.JavaHttpRequestBodyPublisher$ReadableByteChannelSubscription$readData$1.invokeSuspend(JavaHttpRequestBodyPublisher.kt:107)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
... 4 more
Caused by: java.lang.IllegalStateException: closed
at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
at okio.RealBufferedSource.read(RealBufferedSource.kt:269)
at okio.RealBufferedSource.read(RealBufferedSource.kt:77)
at [dev.voqal.sG](http://dev.voqal.sg/)$a.invoke(SourceFile:34)
at [dev.voqal.sG](http://dev.voqal.sg/)$a.invoke(SourceFile:30)
at io.ktor.client.request.forms.FormDslKt$append$2.invoke(formDsl.kt:193)
at io.ktor.client.request.forms.FormDslKt$append$2.invoke(formDsl.kt:193)
at io.ktor.client.request.forms.MultiPartFormDataContent.writeTo(FormDataContent.kt:122)
at io.ktor.client.engine.java.JavaHttpRequestKt$convertToHttpRequestBody$2$1.invokeSuspend(JavaHttpRequest.kt:74)
at io.ktor.client.engine.java.JavaHttpRequestKt$convertToHttpRequestBody$2$1.invoke(JavaHttpRequest.kt)
at io.ktor.client.engine.java.JavaHttpRequestKt$convertToHttpRequestBody$2$1.invoke(JavaHttpRequest.kt)
at io.ktor.utils.io.CoroutinesKt$launchChannel$job$1.invokeSuspend(Coroutines.kt:147)
... 8 more

**Comment by BFergerson** [comment]
I'm having trouble researching this. If it happens again, please include the logs that are generated when it happens.

You can find logs here:
![image](https://github.com/voqal/voqal/assets/3278877/eff15cba-4ed5-4787-a971-51e217a96f5c)

**Comment by modgeosys** [comment]
From the log:
8:56 AM [INFO] Voqal initialized. Version: 2024.3.0
8:56 AM [INFO] Bridge service initialized for project: HealthTechStartups
8:56 AM [INFO] Starting speech service
8:56 AM [INFO] Extracted natives to: /var/folders/ry/p5sprmk161959jvs4hlwvc9c0000gn/T/voqal-natives - Project: HealthTechStartups
8:56 AM [INFO] Intent detector disabled
8:56 AM [INFO] Sending telemetry data to Voqal
8:56 AM [INFO] Cobra version: 2.0.0
8:56 AM [INFO] Listening for wake word...
8:56 AM [INFO] Setting initial status to enabled
8:56 AM [INFO] Status changed from DISABLED to ENABLED
8:56 AM [INFO] Using audio format: PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian
8:56 AM [INFO] Available microphones: [Default Audio Device, version Unknown Version, MacBook Pro Microphone, version Unknown Version, Microsoft Teams Audio, version Unknown Version]
8:56 AM [INFO] Starting shared audio capture. Using microphone: Default Audio Device
8:56 AM [INFO] Voqal initialized. Version: 2024.3.0
8:56 AM [INFO] Bridge service initialized for project: Experimental
8:56 AM [INFO] Starting speech service
8:56 AM [INFO] Extracted natives to: /var/folders/ry/p5sprmk161959jvs4hlwvc9c0000gn/T/voqal-natives - Project: Experimental
8:56 AM [INFO] Using wake provider: None. Skipped booting Picovoice detectors
8:56 AM [INFO] Sending telemetry data to Voqal
8:56 AM [INFO] Setting initial status to enabled
8:56 AM [INFO] Status changed from DISABLED to ENABLED
8:56 AM [INFO] Using audio format: PCM_SIGNED 16000.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian
8:56 AM [INFO] Available microphones: [Default Audio Device, version Unknown Version, MacBook Pro Microphone, version Unknown Version, Microsoft Teams Audio, version Unknown Version]
8:56 AM [INFO] Starting shared audio capture. Using microphone: Default Audio Device
8:56 AM [INFO] Voqal initialized. Version: 2024.3.0
8:56 AM [INFO] Bridge service initialized for project: fhir-ai-ms
8:56 AM [INFO] Starting speech service
8:56 AM [INFO] Extracted natives to: /var/folders/ry/p5sprmk161959jvs4hlwvc9c0000gn/T/voqal-natives - Project: fhir-ai-ms
8:56 AM [INFO] Using wake provider: None. Skipped booting Picovoice detectors
8:56 AM [INFO] Sending telemetry data to Voqal
9:00 AM [INFO] Wake word detected
9:00 AM [INFO] Status changed from ENABLED to LISTENING
9:00 AM [INFO] Playing resource: notification/listening
9:00 AM [INFO] Developer talking: true
9:00 AM [INFO] Developer talking: false
9:00 AM [INFO] Status changed from LISTENING to TRANSCRIBING
9:00 AM [INFO] Leopard version: 2.0.0
9:00 AM [INFO] Sending speech to TTS provider: openai
9:00 AM [SEVERE] Failed to process transcription
9:00 AM [WARNING] closed
9:00 AM [INFO] Status changed from TRANSCRIBING to ERROR
9:00 AM [INFO] Sending telemetry data to Voqal

**Comment by modgeosys** [comment]
Note that I am using OpenAI for everything except the wake word.

**Comment by BFergerson** [comment]
@modgeosys, how often does it happen? Every time? I will add some better error handling code, but in the meantime, could you switch providers? If you install https://github.com/ahmetoner/whisper-asr-webservice, you can use something reasonably close to OpenAI's version but on your local machine for free.

I understand that's not a solution. I can privately provide the 2024.4.0 later today, which will include the [latest features](https://docs.voqal.dev/development/changelog#unreleased) as well as better error handling for this error.

**Comment by BFergerson** [comment]
@modgeosys, okay, I've recreated it. I had to disable and re-enable the internet connection to cause it. So it seems like your network might have had some hiccups while the plugin was running. Working on a fix.

**Comment by modgeosys** [comment]
Actually, it was happening every time I tried to use the plugin.  I should add that it also causes PyCharm to hang when shutting down, requiring me to kill the process before I can restart the IDE.
